"""Generate deterministic circular matrix-void geometry on an M6 RVE.

This M7 generator consumes an already valid M6 multi-particle geometry
record and augments it with Version-1 circular matrix-phase voids.

The validated M6 particle geometry is not regenerated or modified.

Version-1 voids are true geometric holes intended for later subtraction
from the solid RVE. They must maintain strictly positive requested
clearances from reinforcing particles, other voids and the external
RVE boundary.

This file performs geometry-metadata generation only. It does not build
a Gmsh mesh or solve a finite-element problem.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
from numpy.random import Generator, PCG64


M6_GEOMETRY_SCHEMA = "m6_random_microstructure_v1"
M7_GEOMETRY_SCHEMA = "m7_void_microstructure_v1"

VOID_ARRANGEMENT = (
    "random_uniform_matrix_void_rejection_v1"
)

FLOAT_TOLERANCE = 1.0e-12


@dataclass(frozen=True)
class Void:
    """One circular Version-1 matrix-phase void."""

    void_id: int
    center_x: float
    center_y: float
    radius: float


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Add deterministic circular matrix voids to a valid "
            "M6 multi-particle geometry record."
        )
    )

    parser.add_argument(
        "--source-geometry-json",
        type=Path,
        required=True,
        help=(
            "Valid M6 geometry JSON generated by "
            "src/14_generate_m6_random_microstructure.py."
        ),
    )

    parser.add_argument(
        "--output-json",
        type=Path,
        required=True,
        help="Destination for the M7 geometry metadata JSON.",
    )

    parser.add_argument(
        "--void-seed",
        type=int,
        required=True,
        help="Independent deterministic PCG64 seed for void placement.",
    )

    parser.add_argument(
        "--void-count",
        type=int,
        required=True,
        help=(
            "Requested number of circular voids. "
            "Zero is allowed for the M6 no-void regression limit."
        ),
    )

    parser.add_argument(
        "--void-radius-min",
        type=float,
        required=True,
    )

    parser.add_argument(
        "--void-radius-max",
        type=float,
        required=True,
    )

    parser.add_argument(
        "--min-void-particle-spacing",
        type=float,
        required=True,
    )

    parser.add_argument(
        "--min-void-void-spacing",
        type=float,
        required=True,
    )

    parser.add_argument(
        "--min-void-boundary-spacing",
        type=float,
        required=True,
    )

    parser.add_argument(
        "--max-placement-attempts",
        type=int,
        default=10000,
        help=(
            "Maximum candidate attempts for each requested void. "
            "Default: 10000."
        ),
    )

    return parser.parse_args()


def validate_inputs(args: argparse.Namespace) -> None:
    """Validate requested M7 void-generation inputs."""

    if args.void_seed < 0:
        raise ValueError(
            "void-seed must be a non-negative integer."
        )

    if args.void_count < 0:
        raise ValueError(
            "void-count must be a non-negative integer."
        )

    if (
        not np.isfinite(args.void_radius_min)
        or not np.isfinite(args.void_radius_max)
        or args.void_radius_min <= 0.0
        or args.void_radius_max <= 0.0
        or args.void_radius_min > args.void_radius_max
    ):
        raise ValueError(
            "Require 0 < void-radius-min <= void-radius-max."
        )

    spacing_values = {
        "min-void-particle-spacing": (
            args.min_void_particle_spacing
        ),
        "min-void-void-spacing": (
            args.min_void_void_spacing
        ),
        "min-void-boundary-spacing": (
            args.min_void_boundary_spacing
        ),
    }

    for name, value in spacing_values.items():
        if (
            not np.isfinite(value)
            or value <= 0.0
        ):
            raise ValueError(
                f"{name} must be finite and strictly positive."
            )

    if args.max_placement_attempts <= 0:
        raise ValueError(
            "max-placement-attempts must be a positive integer."
        )


def sha256_file(path: Path) -> str:
    """Return SHA-256 for one file."""

    digest = hashlib.sha256()

    with path.open("rb") as handle:
        for block in iter(
            lambda: handle.read(1024 * 1024),
            b"",
        ):
            digest.update(block)

    return digest.hexdigest()


def load_m6_geometry(path: Path) -> dict:
    """Load and minimally validate the source M6 geometry record."""

    if not path.is_file():
        raise FileNotFoundError(
            f"Source M6 geometry file does not exist: {path}"
        )

    data = json.loads(
        path.read_text(
            encoding="utf-8"
        )
    )

    if data.get("schema") != M6_GEOMETRY_SCHEMA:
        raise ValueError(
            "Unsupported M6 geometry schema: "
            f"{data.get('schema')!r}"
        )

    if data.get("status") != "valid":
        raise ValueError(
            "M7 void generation requires an M6 geometry "
            "record with status='valid'."
        )

    if "rve" not in data:
        raise ValueError(
            "M6 geometry record is missing 'rve'."
        )

    if "particles" not in data:
        raise ValueError(
            "M6 geometry record is missing 'particles'."
        )

    width = float(
        data["rve"]["width"]
    )
    height = float(
        data["rve"]["height"]
    )

    if (
        not math.isfinite(width)
        or not math.isfinite(height)
        or width <= 0.0
        or height <= 0.0
    ):
        raise ValueError(
            "M6 RVE width and height must be finite and positive."
        )

    particles = data["particles"]

    if not isinstance(particles, list):
        raise ValueError(
            "M6 'particles' must be a list."
        )

    if len(particles) <= 0:
        raise ValueError(
            "M6 geometry must contain at least one particle."
        )

    reconstructed_particle_area = 0.0

    for expected_id, particle in enumerate(
        particles,
        start=1,
    ):
        particle_id = int(
            particle["particle_id"]
        )
        center_x = float(
            particle["center_x"]
        )
        center_y = float(
            particle["center_y"]
        )
        radius = float(
            particle["radius"]
        )

        if particle_id != expected_id:
            raise ValueError(
                "Particle IDs must remain consecutive and ordered "
                "from 1 through particle_count."
            )

        if (
            not math.isfinite(center_x)
            or not math.isfinite(center_y)
            or not math.isfinite(radius)
            or radius <= 0.0
        ):
            raise ValueError(
                f"Invalid numerical data for particle {particle_id}."
            )

        boundary_gap = min(
            center_x - radius,
            width - center_x - radius,
            center_y - radius,
            height - center_y - radius,
        )

        if boundary_gap < -FLOAT_TOLERANCE:
            raise ValueError(
                f"Particle {particle_id} lies outside the RVE."
            )

        reconstructed_particle_area += (
            math.pi * radius**2
        )

    generated_geometry = data.get(
        "generated_geometry",
        {},
    )

    if "particle_area" in generated_geometry:
        metadata_particle_area = float(
            generated_geometry["particle_area"]
        )

        if not math.isclose(
            reconstructed_particle_area,
            metadata_particle_area,
            rel_tol=0.0,
            abs_tol=1.0e-12,
        ):
            raise ValueError(
                "Particle area reconstructed from M6 radii does "
                "not match M6 generated_geometry metadata."
            )

    return data


def circle_surface_gap(
    first_x: float,
    first_y: float,
    first_radius: float,
    second_x: float,
    second_y: float,
    second_radius: float,
) -> float:
    """Return circle-to-circle surface gap."""

    return (
        math.hypot(
            first_x - second_x,
            first_y - second_y,
        )
        - first_radius
        - second_radius
    )


def void_particle_surface_gap(
    candidate_x: float,
    candidate_y: float,
    candidate_radius: float,
    particle: dict,
) -> float:
    """Return candidate-void to particle surface gap."""

    return circle_surface_gap(
        candidate_x,
        candidate_y,
        candidate_radius,
        float(particle["center_x"]),
        float(particle["center_y"]),
        float(particle["radius"]),
    )


def void_void_surface_gap(
    candidate_x: float,
    candidate_y: float,
    candidate_radius: float,
    existing: Void,
) -> float:
    """Return candidate-void to existing-void surface gap."""

    return circle_surface_gap(
        candidate_x,
        candidate_y,
        candidate_radius,
        existing.center_x,
        existing.center_y,
        existing.radius,
    )


def boundary_surface_gap(
    center_x: float,
    center_y: float,
    radius: float,
    width: float,
    height: float,
) -> float:
    """Return circular-object to RVE-boundary minimum surface gap."""

    return min(
        center_x - radius,
        width - center_x - radius,
        center_y - radius,
        height - center_y - radius,
    )


def minimum_void_particle_gap(
    voids: list[Void],
    particles: list[dict],
) -> float | None:
    """Return minimum void-particle surface gap."""

    if not voids or not particles:
        return None

    minimum = math.inf

    for void in voids:
        for particle in particles:
            minimum = min(
                minimum,
                void_particle_surface_gap(
                    void.center_x,
                    void.center_y,
                    void.radius,
                    particle,
                ),
            )

    return float(minimum)


def minimum_void_void_gap(
    voids: list[Void],
) -> float | None:
    """Return minimum void-void surface gap."""

    if len(voids) < 2:
        return None

    minimum = math.inf

    for index, first in enumerate(
        voids[:-1]
    ):
        for second in voids[index + 1 :]:
            minimum = min(
                minimum,
                circle_surface_gap(
                    first.center_x,
                    first.center_y,
                    first.radius,
                    second.center_x,
                    second.center_y,
                    second.radius,
                ),
            )

    return float(minimum)


def minimum_void_boundary_gap(
    voids: list[Void],
    width: float,
    height: float,
) -> float | None:
    """Return minimum void-to-external-boundary surface gap."""

    if not voids:
        return None

    return float(
        min(
            boundary_surface_gap(
                void.center_x,
                void.center_y,
                void.radius,
                width,
                height,
            )
            for void in voids
        )
    )


def generate_voids(
    args: argparse.Namespace,
    geometry: dict,
) -> tuple[
    list[Void],
    str,
    str | None,
    int,
]:
    """Generate deterministic circular matrix voids by rejection."""

    width = float(
        geometry["rve"]["width"]
    )
    height = float(
        geometry["rve"]["height"]
    )
    particles = geometry["particles"]

    # The explicit no-void case is the M6 regression limit.
    # It requires no void-sampling region, so return before checking
    # whether requested void dimensions could fit inside the RVE.
    if args.void_count == 0:
        return (
            [],
            "valid",
            None,
            0,
        )

    largest_required_margin = (
        args.void_radius_max
        + args.min_void_boundary_spacing
    )

    if (
        2.0 * largest_required_margin
        >= width
        or 2.0 * largest_required_margin
        >= height
    ):
        return (
            [],
            "invalid",
            (
                "void_radius_and_boundary_spacing_leave_no_"
                "usable_sampling_region"
            ),
            0,
        )

    rng = Generator(
        PCG64(
            args.void_seed
        )
    )

    voids: list[Void] = []
    total_attempts = 0

    for void_id in range(
        1,
        args.void_count + 1,
    ):
        radius = float(
            rng.uniform(
                args.void_radius_min,
                args.void_radius_max,
            )
        )

        x_low = (
            radius
            + args.min_void_boundary_spacing
        )
        x_high = (
            width
            - radius
            - args.min_void_boundary_spacing
        )

        y_low = (
            radius
            + args.min_void_boundary_spacing
        )
        y_high = (
            height
            - radius
            - args.min_void_boundary_spacing
        )

        placed = False

        for _ in range(
            args.max_placement_attempts
        ):
            total_attempts += 1

            center_x = float(
                rng.uniform(
                    x_low,
                    x_high,
                )
            )
            center_y = float(
                rng.uniform(
                    y_low,
                    y_high,
                )
            )

            particle_clearance_ok = all(
                (
                    void_particle_surface_gap(
                        center_x,
                        center_y,
                        radius,
                        particle,
                    )
                    + FLOAT_TOLERANCE
                    >= args.min_void_particle_spacing
                )
                for particle in particles
            )

            if not particle_clearance_ok:
                continue

            void_clearance_ok = all(
                (
                    void_void_surface_gap(
                        center_x,
                        center_y,
                        radius,
                        existing,
                    )
                    + FLOAT_TOLERANCE
                    >= args.min_void_void_spacing
                )
                for existing in voids
            )

            if not void_clearance_ok:
                continue

            actual_boundary_gap = (
                boundary_surface_gap(
                    center_x,
                    center_y,
                    radius,
                    width,
                    height,
                )
            )

            boundary_clearance_ok = (
                actual_boundary_gap
                + FLOAT_TOLERANCE
                >= args.min_void_boundary_spacing
            )

            if not boundary_clearance_ok:
                continue

            voids.append(
                Void(
                    void_id=void_id,
                    center_x=center_x,
                    center_y=center_y,
                    radius=radius,
                )
            )

            placed = True
            break

        if not placed:
            return (
                voids,
                "invalid",
                (
                    "void_placement_failed_for_void_"
                    f"{void_id}"
                ),
                total_attempts,
            )

    return (
        voids,
        "valid",
        None,
        total_attempts,
    )


def build_metadata(
    args: argparse.Namespace,
    source_path: Path,
    source_geometry: dict,
    voids: list[Void],
    status: str,
    failure_reason: str | None,
    total_attempts: int,
) -> dict:
    """Build machine-readable M7 geometry metadata."""

    width = float(
        source_geometry["rve"]["width"]
    )
    height = float(
        source_geometry["rve"]["height"]
    )

    particles = source_geometry["particles"]

    gross_rve_area = (
        width * height
    )

    particle_area = float(
        sum(
            math.pi
            * float(particle["radius"]) ** 2
            for particle in particles
        )
    )

    void_area = float(
        sum(
            math.pi * void.radius**2
            for void in voids
        )
    )

    matrix_area = (
        gross_rve_area
        - particle_area
        - void_area
    )

    solid_area = (
        matrix_area
        + particle_area
    )

    particle_fraction = (
        particle_area
        / gross_rve_area
    )

    void_fraction = (
        void_area
        / gross_rve_area
    )

    min_void_particle_gap = (
        minimum_void_particle_gap(
            voids,
            particles,
        )
    )

    min_void_void_gap = (
        minimum_void_void_gap(
            voids
        )
    )

    min_void_boundary_gap = (
        minimum_void_boundary_gap(
            voids,
            width,
            height,
        )
    )

    requested_void_count_reached = (
        len(voids)
        == args.void_count
    )

    void_particle_spacing_satisfied = (
        min_void_particle_gap is None
        or (
            min_void_particle_gap
            + FLOAT_TOLERANCE
            >= args.min_void_particle_spacing
        )
    )

    void_void_spacing_satisfied = (
        min_void_void_gap is None
        or (
            min_void_void_gap
            + FLOAT_TOLERANCE
            >= args.min_void_void_spacing
        )
    )

    void_boundary_spacing_satisfied = (
        min_void_boundary_gap is None
        or (
            min_void_boundary_gap
            + FLOAT_TOLERANCE
            >= args.min_void_boundary_spacing
        )
    )

    positive_matrix_area = (
        matrix_area > 0.0
    )

    solid_area_consistent = (
        math.isclose(
            solid_area,
            gross_rve_area - void_area,
            rel_tol=0.0,
            abs_tol=1.0e-12,
        )
    )

    particle_area_consistent = True

    source_generated = (
        source_geometry.get(
            "generated_geometry",
            {},
        )
    )

    if "particle_area" in source_generated:
        particle_area_consistent = (
            math.isclose(
                particle_area,
                float(
                    source_generated[
                        "particle_area"
                    ]
                ),
                rel_tol=0.0,
                abs_tol=1.0e-12,
            )
        )

    checks = {
        "source_m6_geometry_valid": (
            source_geometry.get("status")
            == "valid"
        ),
        "requested_void_count_reached": (
            requested_void_count_reached
        ),
        "void_particle_spacing_satisfied": (
            void_particle_spacing_satisfied
        ),
        "void_void_spacing_satisfied": (
            void_void_spacing_satisfied
        ),
        "void_boundary_spacing_satisfied": (
            void_boundary_spacing_satisfied
        ),
        "positive_matrix_area": (
            positive_matrix_area
        ),
        "particle_area_preserved": (
            particle_area_consistent
        ),
        "solid_area_consistent": (
            solid_area_consistent
        ),
    }

    all_checks_passed = all(
        checks.values()
    )

    if (
        status == "valid"
        and not all_checks_passed
    ):
        status = "invalid"

        failed_checks = [
            key
            for key, value
            in checks.items()
            if not value
        ]

        failure_reason = (
            "post_generation_checks_failed:"
            + ",".join(failed_checks)
        )

    source_rng = source_geometry.get(
        "rng",
        {},
    )

    metadata = {
        "schema": M7_GEOMETRY_SCHEMA,
        "status": status,
        "failure_reason": failure_reason,
        "particle_arrangement": (
            source_geometry.get(
                "arrangement"
            )
        ),
        "void_arrangement": (
            VOID_ARRANGEMENT
        ),
        "source_m6_geometry": {
            "path": str(
                source_path
            ),
            "sha256": sha256_file(
                source_path
            ),
            "schema": (
                source_geometry["schema"]
            ),
            "status": (
                source_geometry["status"]
            ),
            "arrangement": (
                source_geometry.get(
                    "arrangement"
                )
            ),
            "particle_seed": (
                source_rng.get(
                    "seed"
                )
            ),
        },
        "rng": {
            "bit_generator": "PCG64",
            "void_seed": (
                args.void_seed
            ),
            "numpy_version": (
                np.__version__
            ),
        },
        "rve": copy.deepcopy(
            source_geometry["rve"]
        ),
        "requested_void_geometry": {
            "void_count": (
                args.void_count
            ),
            "void_radius_min": (
                args.void_radius_min
            ),
            "void_radius_max": (
                args.void_radius_max
            ),
            "min_void_particle_spacing": (
                args.min_void_particle_spacing
            ),
            "min_void_void_spacing": (
                args.min_void_void_spacing
            ),
            "min_void_boundary_spacing": (
                args.min_void_boundary_spacing
            ),
            "max_placement_attempts": (
                args.max_placement_attempts
            ),
            "placement_algorithm": (
                VOID_ARRANGEMENT
            ),
        },
        "generated_geometry": {
            "particle_count": len(
                particles
            ),
            "void_count": len(
                voids
            ),
            "particle_area": (
                particle_area
            ),
            "particle_area_fraction": (
                particle_fraction
            ),
            "void_area": (
                void_area
            ),
            "void_area_fraction": (
                void_fraction
            ),
            "matrix_area": (
                matrix_area
            ),
            "solid_area": (
                solid_area
            ),
            "gross_rve_area": (
                gross_rve_area
            ),
            "minimum_void_particle_surface_gap": (
                min_void_particle_gap
            ),
            "minimum_void_void_surface_gap": (
                min_void_void_gap
            ),
            "minimum_void_boundary_surface_gap": (
                min_void_boundary_gap
            ),
            "total_placement_attempts": (
                total_attempts
            ),
        },
        "checks": checks,
        "particles": copy.deepcopy(
            particles
        ),
        "voids": [
            asdict(void)
            for void in voids
        ],
    }

    return metadata


def write_metadata(
    output_path: Path,
    metadata: dict,
) -> None:
    """Write deterministic formatted JSON metadata."""

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path.write_text(
        json.dumps(
            metadata,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    """Generate one deterministic M7 void geometry metadata record."""

    args = parse_args()

    validate_inputs(
        args
    )

    source_geometry = load_m6_geometry(
        args.source_geometry_json
    )

    (
        voids,
        status,
        failure_reason,
        total_attempts,
    ) = generate_voids(
        args,
        source_geometry,
    )

    metadata = build_metadata(
        args,
        args.source_geometry_json,
        source_geometry,
        voids,
        status,
        failure_reason,
        total_attempts,
    )

    write_metadata(
        args.output_json,
        metadata,
    )

    print(
        json.dumps(
            metadata,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
    )

    return (
        0
        if metadata["status"] == "valid"
        else 2
    )


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
